#!/usr/bin/env bash

eval "$(docopts -V - -h - : "$@" <<EOF
Usage: vbox_backintime [options] [<name>]

      --date DATE        Use DATE as base date, format %Y-%m-%d as in date 
                         command (default: 2015-06-20)
      --now              Set the date to the current host system time
                         (i.e. now, the result of the date command).
      --list             List names of available virtual machines and exits.
      -v, --verbose      Generate verbose output.
      -h, --help         Show this help message and exits.
      --version          Print version and copyright information.
----
vbox_timemachine 0.5.0
copyright (c) 2015 Cristian Consonni
MIT License
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
See https://github.com/CristianCantoro/vbox_timemachine for more info.
EOF
)"

#### some useful global variables and functions ####

# current time (i.e. host system time) in millisecond from Epoch
NOW=$(($(date +%s%N)/1000000))

### date default ###
# Every date is expressed in millisecond from Epoch
# You can change it using a tool like http://www.epochconverter.com/
#
# Epoch timestamp: 1434788129
# Timestamp in milliseconds: 1434788129000
# Human time (GMT): Sat, 20 Jun 2015 08:15:29 GMT
# Human time (your time zone): sab 20 giu 2015 10:15:29 CEST
DATE_DEFAULT=1434788129000

list_vms() {
    # Preparing virtual box names array, converting spaces to tildes
    local vmslist
    vmslist="$( vboxmanage list vms \
              | awk  -F'{' '{printf $1";"}' \
              | sed 's/ ;/;/g' \
              | sed 's/ "/"/g' \
              )"

    # split vms list into an array called vms
    # https://stackoverflow.com/
    #   questions/10586153/split-string-into-an-array-in-bash
    IFS=';' read -a VMS <<< "$vmslist"
    
    # No. of virtual machines
    NVMS="${#VMS[@]}"

    # Range of numbers from 0 to NVMS (included)
    local num_vms
    num_vms="${!VMS[@]}"

    # transform tilde back to spaces
    for i in $num_vms ; do 
        VMS[$i]=$( echo ${VMS[$i]} )
    done

    for i in $num_vms ; do 
        printf "%s: %s\n" "$i" "${VMS[$i]}"
    done

}

#### ####

if [ -z "$name" ] ; then

    echo "Available virtual machines:"
    list_vms

    while true; do
        echo -n "-> Select the VM no.: "
        read reply
        echo
        if [[ "$reply" =~ ^[0-9]+$ ]]; then
            if [ $reply -ge 0 -a $reply -le $((NVMS-1)) ] ; then
                break
            else
                echo "Selection must be a number between 0 and $((NVMS-1))."
                echo
            fi

        else
            echo -n "Error: $reply is not an integer."
            echo "Selection must be a number between 0 and $((NVMS-1))."
            echo
        fi
    done

    name="${VMS[$reply]}"
fi

if $verbose ; then
    unquoted_name="${name%\"}"
    unquoted_name="${unquoted_name#\"}"
    echo "Will modify the virtual machine named: $unquoted_name"
    echo
    echo "Current system time is: $(date)"
    echo "Current system time is (milliseconds from epoch): $NOW"
    echo
fi

if $list ; then
    echo "Available virtual machines:"
    list_vms

    echo "No. of available VMS: $NVMS"
    exit 0

fi

baseline=$DATE_DEFAULT

if [ ! -z "$date" ] ; then
    base_date=$(date -d "$date" +%s)
    baseline=$((base_date*1000))
fi

offset=$(($baseline-$NOW))

if $now ; then
    offset=$((0))
fi

if $verbose ; then
    echo "Offset in milliseconds is: $offset"
    echo "Base date is (milliseconds from epoch): $baseline"
    echo "Base date is: $(date -d @$((baseline/1000)) +'%d-%m-%Y %T %z')"
    echo    
fi

echo "vboxmanage modifyvm $name --biossystemtimeoffset $offset"
echo
# xargs' -L1 is implied by -I
echo $name | xargs -I {} vboxmanage modifyvm {} --biossystemtimeoffset $offset
